proxy:
  title: ShinyProxy
  port: 8080
  hide-navbar: false
  container-log-path: /container-logs
  docker:
    internal-networking: true
    container-network: sp-example-net
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: "${proxy.docker.container-network}"
  - id: hello_world
    display-name: Hello World
    description: This is the basic shiny example
    container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
    container-image: thomasvyu/shiny-hello-world:latest
    container-network: "${proxy.docker.container-network}"
  - id: hello_world_synlogin
    display-name: Hello World Synapse Login
    description: This is the basic shiny example
    container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
    container-image: thomasvyu/shiny-hello-world:syn-login
    container-network: "${proxy.docker.container-network}"
  - id: dca_test
    display-name: DCA
    description: This is data curator app
    # container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/app')"]
    container-image: ghcr.io/sage-bionetworks/data_curator:0.3.10-beta
    container-network: "${proxy.docker.container-network}"
    container-env:
      SECRETS_MANAGER_SECRETS: '{"DCA_SCHEMATIC_API_TYPE":"offline","DCA_CLIENT_ID":"100127","DCA_CLIENT_SECRET":"","DCA_APP_URL":"http://127.0.0.1:8100"}'

logging:
  file:
    /log/shinyproxy.log

# server:
#   servlet:
#     context-path:  /